#pragma once
#include "SDK.h"
#include "Util.h"
#include "TextFile.h"
#include <sstream>

class CKillSay : public IGameEventListener2
{
public:

	//void Run(CBaseEntity * pLocal, CUserCmd * pCommand);

	void InitKillSay();

	void FireGameEvent(IGameEvent * event);

	bool wasEventInitialized = false;

	std::string repeat(int n, const char* str)
	{
		std::ostringstream os;
		for (int i = 0; i < n; i++)
			os << str;
		return os.str();
	};

	TextFile killsayFile{};

};

namespace KillSay
{
	const std::vector<std::string> ncc =
	{
		"%name%, you are a noob.", "%name%, do you even lift?", "%name%, you're a faggot.", "%name%, stop cheating.",
		"%name%: Mom, call the police - I've got headshoted again!", "Right into your face, %name%.",
		"Into your face, pal.", "Keep crying, baby.", "Faggot. Noob.", "You are dead, not big surprise.",
		"Sit down nerd.", "Fuck you with a rake.", "Eat a man spear, you Jamaican manure salesman.",
		"Wallow in a river of cocks, you pathetic bitch.", "I will go to heaven and you will be in prison.",
		"Piss off, you poor, ignorant, mullet-wearing porch monkey.",
		"Your Mom says your turn-ons consist of butthole licking and scat porn.",
		"Shut up, you'll never be the man your mother is.",
		"It looks like your face caught on fire and someone tried to put it out with a fork.",
		"You're so ugly Hello Kitty said goodbye to you.",
		"Don't you love nature, despite what it did to you?"
	};

	const std::vector<std::string> niggerhook =
	{
		"%name%, I would call you cancer, but cancer actually kills.",
		"I just owned %name%.",
		"Mad? %name%",
		"%name% is mad because he died in a 10 year old dead source game :(",
		"%name% I PRAY TO GOD A PACK OF WOLVES RAPES YOU IN THE DEAD OF WINTER AND FORCES YOU TO WALK HOME BAREFOOT!",
		"wow %name% destroid p.s. ur utter shit",
		"ww %name% SNAPPED u HARD (fkn shitter)",
		"%name% did u kno if u take ld and replace L with B, u get BD, and thats u",
		"LMFAO nt %name% retard ===--D~~ (cum)",
		"{{R@PeD}} :: btw you are shit %name%",
		"%name% is the reason why abortion is legal.",
		"%name% hope ur ok with going on utube!!",
		"%name% is a fuckin fagot LoLOLolLOLO!!!!",
		"%name% Ll did u just buy dis game??!? ROFRRL",
		"LMAO %name% u got SMASHD!! (and your dad fingers you)",
		"%name% loL :D get bttr fgt (jk u cant)",
		"%name% < SPRM (ESP UR DADZ LL) ~~~c====",
		"<--- BEATDOWN BRINGA (%name% smashed u dickhead)",
		"%name%!! rFL shat on -- ****nice play faggt****",
		"%name% u suck dicks nigger go uninstall",
		"%name%, wer u born yesterday??? ~~ ROFL shtty",
		"%name% do you feel special? Please try suicide again... hopefully you will be successful this time.",
		"%name% u did good.... for a fCKing~BADDIE...sht on",
		"%name% lolURbd at an E-Z GAME (>^^)>",
		"%name% go milk a cow you shitmongering cuntnugget",
		"%name% = vrgin nrd~",
		"rekt nerd",
		"%name% cheer up^ :) youre small dk isnt noticealbe under ur BaDnEsS",
		"==----**~~#NOOB DOWN#~~**----==",
		"%name% NEWSFLASH NIGGA U AINT JEZUZ, NO  CAN BE JEZUZ LIKE H E WAS NIGGA U TIHNKIN U CAN?",
		"%name% rack off you crazy little dingo!!! FFS????@!",
		"%name% LL :-) LL u gt rPD idt :-) LL",
		"%name% nt nigger (suck my cunt)",
		"%name% **maybee** if u stoped jerkin it to anime u'd get a gf ^______^",
		"hey %name%, its a gay virgn",
		"%name% CRY SOME MORE - Team Fortress 2 Heavy Weapons Guy",
		"at least i have arms n legs (thats what it feels like playing vs %name%)",
		"i laffed iRL b-cuz your so BAD %name% *(<(<(OEWNED>)>)*",
		"%name% you little fuckmunch of obliverating asswipe ",
		"%name% GO BACK TO ASS-LAND YOU DICK-CODDLING PRINCE!",
		"**PROTIP** If you wanna frag people you have to hit them, %name%.",
		"**PROTIP** Use the reticule in the middle of the screen to aim, %name%.",
		"%name% do you feel special? Please try suicide again... hopefully you will be successful this time.",
		"**PROTIP** Your crosshair generally assists you in aiming.",
		"rofl pubbers like %name% are so bad its funny",
		"LOL WOW watchin %name% play this game is like watching helen keller play tennis",
		"%name% ahaha ur awful",
		"%name%: i luv anime!!11",
		"%name% lolumad",
		"calm down %name%, ur bad, just accept it",
		"ROFL WOW BADDIES EVERYWHERE JUST LOOK AT %name%",
		"qq  qq  qq q qq QQ %name%",
		"%name% poop on a noob autismal butfrustrated etc etc",
		"LMDOIUE %name% (laf my dik off into ur ear)",
		"%name% u hav week  live cuz u dying of stage  --own--",
		"%name% your eyes leak cum when u cry and you swallow it when it runs down your cheeks, gay noob",
		"%name% ur such a looser ur wife is paper bag",
		"%name% u so asspissed rite now ur bluddy poo steam w/rage",
		"%name% y dont u gbgayville ur dad is wait",
		"how dos it fel b autism %name%?",
		"%name% get the weiner out of your mouth, ShitFUckeDDDDD!~@#(",
		"%name% ay are u Oscar teh grouch!?!? CUZ U LIV INA TRASHCAN!!!!!!!!!??",
		"%name% lmfao ur an moron",
		"%name% status: fucked [x] not fucked [ ] ",
		"%name% = rekt",
		"%name% don't hate me because I'm beautiful hate me because your boyfriend thinks so ~~~~",
		"%name% hang urslef from a high cieling, u candy apple jabroni >:(",
		"I took ur mom out to a nice steak dinner, but rly it was my evil twin with ur mmm and I was at your house raping your father",
		"%name% g rub your cock against a cheese grater you titcrapping twigfucker",
		"%name% u only even touchin me cause my girl is screamin, im not gonna take a loss that aint legit -- i poop on u, im jus distracted",
		"%name% Your mother swims out to meet troopships.",
		"%name% your eyes leak cum when u cry and you swallow it when it runs down your cheeks, gay noob ",
		"%name% shut the fuck up, you cock juggling thundercunt ",
		"%name% ur butt's a testing ground for TD bombs - thermodicklear ",
		"%name% everyone who loves you is wrong. ",
		"%name% go climb a wall of dicks. ",
		"%name% you're as dumb as a bag of doorknobs. Retarded doorknobs. ",
		"%name% ur butt is like CAPITAL of the BUTT DUMBPSTER factory - u take the cum that no ordinary man could ",
		"Looks guys, a one man fag parade! ",
		"you must be a DIRTY, STINKING, GREESY HAIRED, CHEESY BREATH CUNT. ",
		"%name%, you are what you eat, and you're a dick. ",
		"%name% get the fuck out of my server you disgusting cum guzzling fuck puppet ",
		"%name% your mother will die aborting my child. ",
		"%name% go cry about it on ur facebook (except opps u have no friends nerd) ",
		"%name% is a disgusting crusty cum drenched cum sock ",
		"%name% i will puss in ur cumdumbtser ",
		"%name% are you? retarted? ",
		"%name% ur dog looks like a faggot ",
		"%name% is a faggot",
		"%name% your hair is a jizzmop and ur mouth is a shit depository and ur butts a FDA Approved Cum Processing Facility ",
		"i shld slap u in the tits %name%",
		"%name% yor dad calls u 'cc'  cumcaptin lawl ",
		"%name% in gradeschol u wanted to b a butplumber when u grw up ",
		"horse status: fucked [x] not fucked [ ] ",
		"%name% your facebok status = shitslaming fukfaced dickpipeing aspie ",
		"%name% i called u a fukin nerd go blog abut it faggt ",
		"'i like to eat dady's steemy logs of poop  lunsh n diner while jackling of to naurto' - %name%",
		"%name% confratulasons u ar the new WORLD BUTTHURTED CHAMPEON ",
		"%name% got first place in GETING OWND bY ME ",
		"rep up those wieners cos ur sure hungry for one ",
		"%name% can u b anny more anal hurt rigt now???? ",
		"%name% gb pussybaby land where u git ownd by dick ",
		"%name% lol u troled so fukin hard u wan sum ice for the ASSBURN?? ",
		"%name% u cry tears of blud and cum ur mom's penis out your angry butthole ",
		"I hav neer seen sum so pooper peeved %name% ",
		"%name% u ned to take chilpil and stop raping your ownasswit with husband ",
		"'omg i love sukn dicks and crying to link park' - %name%",
		"%name% ur butt is evaporating cum bcuz it is steaming wit anger ",
		"SUMBUDY is anally anguished ",
		"%name% lol ur so bad u cant even find ur own dick ",
		"%name% ur dad rapes u with peanut butter,shitty ",
		"%name% whats that? oh, must be the sound of u getting creamed in the face by my grandfather baddy",
		"u were --- this close to being recognized by ur parents",
		"%name% REALLY? what a fucking retraded cunt",
		"%name% im gonna stick an egg in ur vaginal canal and punch it-",
		"%name% youve just been HURT FEELINGS'd",
		"i bet u have a fetish FOR MEN LMAO",
		"%name% ur just so madd all the time its  easy  own u",
		"'i like to drnikj sperm from my sperm bottle while waring my sperm necklace' - %name%",
		"%name% go drink ur moms bredst milk u fart commander",
		"%name% wolth with a T-rex cock! what is the odds",
		"%name% fail. really? U must b gay and a nigger",
		"rofl who the hell are these fools",
		"%name% stfu nerd go grow balls",
		"%name% are you serious you dumb bastard? you faggot as bitch cunt, i will piss in your mouth",
		"%name% i feel like your dad after a morning fuck with your sister.. ",
		"sdlkjyfgretsyhesrerdxth sorry just fucking %name%'s mom on the keyboard",
		"I feel like Zeus after a morning fuck with Athena",
		"%name%, i'm assuming that your a preteen in the u.s. with a cracking voice that has to hide his wet dream stained sheets",
		"i wish my girlfriend was as dirty as that shot, %name%",
		"%name% go back to grooming your neck-beard. By the way you've got homework due tomorrow.",
		"'I came all over my triple chins.' - %name%",
		"top 10 faggots of 2007 - number 1 - %name%",
		"%name% you got knocked the fuck out",
		"%name% buttdocktor evaluation: BUTTBLEED",
		"%name% do u jus liev in ur own lil'' world u dumFUK??",
		"PERRRRRRRRRRRRRRRRRRRRRRRRRRRRKELE %name%",
		"%name% take a gun, put it in your mouth and pull the trigger",
		"%name%, you are the smallest little shit I've ever seen, yet you are so amazingly funny.",
		"%name% lol nigga hold on let me hit dis shot b u tell me how fly i am ------- aiight you can tell me now",
		"%name% let me call my gf and get the name of her gynecologist, you seem to need one",
		"psycho!, take it deep meat bag!! i hope the place u live burns to the ground!",
		"%name% just do the WORLD a Big fucking favour and just ROLE OVER AND FUCKING DIE",
		"HAHAHAH SO FUCKING BAD %name% KILL YOURSELF LMFAO",
		"%name% noone will care when you die dumb cunt",
		"%name% = nigger",
		"%name% ur so analmad n i dont even care",
		"%name% deal w it gaylord",
		"%name% enjoyn ur buttfrustration?",
		"%name% u got wned",
		"%name% ur just a petatic nerd",
		"%name% colonrampage'd",
		"%name% yu're tears feul my butownage",
		"%name% get ur mom  lik teh tears of ur ballz, assmaster",
		"%name% y r u so paind in the glute LOL",
		"%name% i shit on niggers like u all da godbdamn time lmao",
		"cocks ahoy %name%",
		"%name% I RECOMMEND YOU TRY ANOTHER SPORT. LIKE KNITTING.",
		"%name% YOU FUCKIN' FINGERBANGED YOUR COUSIN MAN. THAT'S A FUCKING FACT.",
		"%name% shitty little crotch fruit",
		"%name% i've never seen anyone so SPHINCTER SORE b lmao",
		"%name% ur BUTTSTEAM is causing globul warming",
		"all my diks r laffing semen n ur nostrils %name%",
		"%name% ur gay boyfriends (u have like .  LOL) use chapstick for lube",
		"%name% u seem  have analchafe, would u like a RAGE enema?",
		"%name% you're mom was a man's anus WWROFL",
		"%name% go jump in a lake ful of penises you portugeese masticator",
		"%name% i would rite more about wning u but i dont speak AUTISM",
		"%name% i will puss in ur mouth u stupid nigger",
		"'Y do so mny ppl make fun of my fetish for artichokes' - ur furaffinity blog",
		"%name% got aborted like my ex-gf's baby",
		"raped with ease by an acne-ridden anime-watching virgin",
		"%name% remember that one time u werent a gigantic fellatioqueen? me neither",
		"raped w/ ease %name%",
		"they call me the nigger killer, %name% ",
		"raped u faster than a turtle flys %name%",
		"if i put penut butter on my balls u'd lick it off probably, shitty %name%",
		"%name%, my dog is smarter and smells better than you",
		"wow, welcome to shitlord-land :: populashion - %name% ::",
		":::: APPROACHING FAGGOT CITY LIMITS :::: TURN BACK NOW ::::",
		"%name% if i had the choice of fucking your face or having sex w/ jessica alba, i'd shit on your lips and make u eat it",
		"%name% rofl im literally not even aiming right now",
		"%name% oh are you angry? peeved? perturbed?",
		"%name% i just dropped u like ehfk does wit his ubers ROLF",
		"%name% difference between you and a dead kid? i would fuck the dead kids face bc he's attratctive LOL",
		"cum-captin reporting in, target acquired, 'i'm a fag' - %name%",
		"%name% go to an animal shelter an pick up a kitten, only way ur ever gettin pussy nerd virgin",
		"nothing in my life has prepared me for seeing a true idiot like %name% play vidoegames",
		"%name% i bet a  yr old cancer patient w/ terminel ballsack cancer has a bettewr life than u, homo",
		"maybe if u werent so shit u might be good lol fagnet",
		"%name% lL get SHTTED on u bad turdkid",
		"%name% prawned u fukin fatty fuck",
		"%name% mushed u dorkfuck nerd",
		"%name% you just got owned by a sponsored, professional gamer.",
		"lmfao ur an moran %name%",
		"HEaD$hT Nb %name%",
		"%name% poned hard kid",
		"%name% kid u dident survive",
		"%name% ur under arrested for being shit",
		"%name% ur trash kid",
		"%name% STUNNING REALISATION: U r ReALlY fUKiN BAd aT ths game kid",
		"%name% u have da right  be shit at games(o wait u already r lol)",
		"%name% stop get stuck in door u fat fuck then i wont headsht u",
		"%name% funny kid, u dont look like a fish so how come u gettin fucking BATTERED!!!!!",
		"%name% you shud hold a funeral for my dick cos i buried it in ur MOM!!! lOL!!! c=======",
		"outskilled %name%",
		"%name% u make gettin wrecked look easy kid.. go back  ur mams tit",
		"%name% $|_ShiTTeR**DeAd_ShiTTeR_|$-___-$|DA tRaNsFoRmAtIoN hAs beGuN|*",
		"%name% <<SHITTER STATUS: WRCKeD!!!>>>",
		"%name% CN aLL SHTTERS PLz bRD DA SHttErTrAIN, DESTnATIN: U JUST gT Fu|<In SmShED CHOO CHOO",
		"%name% absOLUTEly WRECKED hahaha u fat mongal",
		"%name% LOL u got fkne FOLDED u stuped fat dork",
		"%name% FKN dork this a fps U Cant cast ur nerd spells!!! OWN ED!!!",
		"%name% ur dads bummin ur faace u fat bent gay::GET MUNCHD",
		"%name% #_roooooooooooooFL WREKCED U FUKN PIZZA FACE DORK",
		"%name% is the number 1 attendee of university of bein a FUKING FAGET",
		"rofl did any see that dork get raped",
		"%name% how i turn up difficulty in this shit serveR??",
		"%name% LOL does this kid even have arms?? he so fuken SHIT!! hahahha",
		"%name% poned u fat pussy get out ur mams basement",
		"%name% hahaha go cry ure dads dick forever noob(pwned)",
		"%name%? more like \"im a fuckin nigger\" lmao rekt",
		"% name % I am sure you will do really well for the rest of this round, Cap'n Neckbeard of the SS Obesity.",
		"% name % ur such a virgin you could make ur own brand of olive oil rofl~",
		"% name % i bet the last time u felt a breast was in a kfc bucket",
		"you guys are failers",
		"% name % CAN YOU PLEASE NOT BE SHIT",
		"% name % you were just a turd out there",
		"% name % can u stop sucking dicks so much ?",
		"'my ass bleeds' - % name %",
		"% name % just gor raped",
		"% name % confirmed for Captain Buttmad of S.S.Rectally Devastated",
		"% name % not a million poets in a million years could describe how much your ass hurts",
		"are u gay, % name %?",
		"are u actually that gay, % name %?",
		"% name % 's butt integrity: 0%",
		"% name % is a niggerjew roflmao",
		"% name % how do u even sit down after that sphincter spearing lmao",
		"% name % ur butt deserves to be in a museom for FAGS",
		"% name % every time u see a male nurse you get an  eerection U HOMO",
		"'i wish i cud gurgle all the spoog and munch all the poop in the umiverce so i culd be cum n shit master' - % name %",
		"% name % only thing left u do in this world is to go all out and comitt BUTTSUICIDE",
		"d % name % id u ever concider not being so fukin MAD?",
		"% name % = bad.",
		"% name % nice try, aspergers",
		"% name %, face it cunt bugle, u have no friends, no skils, no life, no sexs, no nothing",
		"% name % i shit on fools like u all da godbdamn time",
		"BUTTSHIT STATUS: ABSOLUTE SHIT[X] NOT ABSOLUTE SHIT[]",
		"% name % get domed fatty",
		"virgin down",
		"wow % name % that was fkin gay",
		"% name % uffya$$ 1tap $$ sit fucking low kid rifk hhhhhh",
		"Player % name % left the game(timed out)",
		"Player % name % left the game(Disconnect by user.)",
		"Player % name % left the game(VAC banned fom secure server)",
		"Player % name % left the game(steam account globally banned)",
		"Player % name % left the game(VAC banned fom secure server)",
		"% name % is more toxic than the beaches at Fukushima",
		"% name %, don't be upsetti, have some spaghetti",
		"% name %, rest in spaghetti never forgetti",
		"% name %, You're almost as salty as the semen dripping from your mum's mouth",
		"mad cuz bad",
		"% name %, safest place for us to stand is in front of your gun",
		"% name %, Options->How To Play",
		"How do you change your difficulty settings? My TF2 is stuck on easy",
		"% name %, The only thing you carry is an extra chromosome.",
		"% name %, You have the reaction time of a dead puppy.",
		"% name %, idk if u know but it's mouse1 to shoot",
		"% name %, is your monitor on ?",
		"% name %, did you know that tf2 is free to uninstall?",
		"Oops, I must have chosen easy bots by accident",
		"server cvar 'sv_rekt' changed to 1.",
		"% name %, You're the human equivalent of a participation award.",
		"% name %, tf2 is too hard for you m8 maybe consider a game that requires less skill, like idk....solitaire",
		"WOW! % name % imagine if your parents weren't siblings.",
		"Who are you sponsored by % name %? Parkinson's?",
		"% name %, you should have been a handjob",
		"% name %, \\_/ < ----Cry here Africa needs water",
		"% name %, You're the type of player to get 3rd place in a 1v1 match",
		"% name %, Stephen Hawking has better hand - eye coordination than you.",
		"% name %, You're an inspiration for birth control.",
		"% name %, The guy who played CSGO with a wheel is better than you",
		"% name %, I suggest turning your monitor on for improved gaming performance.",
		"% name %, The only problem with your PC is that thing between your keyboard and your chair",
		"% name %, I'm surprised that you were able hit the 'Install' button",
		"% name %, I'd ask you to shoot yourself, but you'd probably still miss.",
		"% name %, I'm pretty sure you've typed more sentences than landed shots.",
		"% name %, If your face was a Counter Strike map, it would be de_formed.",
		"% name %, You're as useful as Stephen Hawking's home gym",
		"% name %, John Lennon is better at dodging bullets than you",
		"% name %, You know this isn't turn based combat right? When they shoot at you feel free to shoot back.",
		"% name %, If you were any more inbred you'd be a sandwich",
		"% name %, Imagine going through a nine month pregnancy only to give birth to someone who can't push the fucking cart.",
		"% name %, I would mentally duel with you, but I can see you're unarmed",
		"% name %, I've never touched a cigarette. I feel a sense of regret for not doing it, because you gave me cancer anyway.",
		"% name %, I'd call all of you cancer, but at LEAST cancer kills.",
		"% name %, You know what man, blind gamers deserve a chance too.I support you.",
		"% name %, You're worth less than a Steam trading card",
		"% name %, You're the reason they need to put instructions on Bleach bottles",
		"% name %, If you were on life support I would pull the plug to charge my phone.",
		"% name %, I envy everyone that hasn't met you.",
		"% name %, I'd like to see something from your point of view, but I can't seem to get my head that far up my ass.",
		"% name %, You're so stupid that if you fell into a barrel of tits you'd come up sucking your thumb.",
		"% name %, If you were any dumber we'd have to water you.",
		"% name %, You should stop playing %class%, you seem pretty bad at it.",
		"%name%, I don't know what your problem is, but ill bet its hard to pronounce.",
		"%name%, Your birth certificate is an apology from the abortion clinic.",
		"Hey %name%! Your mother was a snow blower!",
		"Hey %name%, I'll plant a mango tree in your mom's ass and fuck your sister in its shade.",
		"%name%, Your dad should have shot you on the wall.",
		"%name%, Your face looks like someone tried to put out a forest fire with a screwdriver",
		"%name%, The smartest thing that’s ever come from your mouth was my dick",
		"%name%, Stop crying, you look so fucking fat when you cry.",
		"%name%, Everyone who loves you is wrong.",
		"%name%, Have you ever considered suing your mother for drinking while she was pregnant with you?",
		"%name%, I wish you were retarded, because then you'd at least have an excuse.",
		"%name%, You have the intelligence of a stillborn.",
		"%name%, With a face like yours, I’d be careful who and what I make fun of",
		"%name%, You think you're hot shit but you're really just cold diarrhea.",
		"%name%, You're not worth the money it would have cost to abort you, and I can buy a coat hanger for $2.",
		"%name%, It was a joke not a dick, don't take it so hard",
		"%name%, You look like you smell like pee.",
		"%name%, You're dumb as cow shit and only half as useful.",
		"%name%, I would insult you but nature did a better job.",
		"%name%, You're the reason the gene pool needs a lifeguard.",
		"%name%, If I ate a bowl of alphabet soup, I could shit out a smarter sentence than any of yours.",
		"%name%, 2090 called.You're dead and you wasted your time on earth.",
		"%name%, you did a really good job tying your shoes this morning.We're all really proud of you and what you're able to accomplish.",
		"%name%, You're so ugly, I couldn't pay a ten cent hooker five dollars to fuck ya.",
		"%name%, Yo momma so fat that when she took a teleporter, she telefragged the entire server",
		"%name%, Your moms so ugly, not even spy would disguise as her.",
		"%name%, Two wrongs don't make a right, take your parents as an example.",
		"%name%, Your family tree must be a cactus because everybody on it is a prick.",
		"%name%, You're so ugly, when your mom dropped you off at school she got a fine for littering.",
		"%name%, If laughter is the best medicine, your face must be curing the world.",
		"%name%, You must have been born on a highway because that's where most accidents happen.",
		"%name%, If ignorance is bliss, you must be the happiest person on earth.",
		"%name%, You are proof that evolution CAN go in reverse."
	};

}

extern CKillSay gKillSay;

